// RAMP_RPM_Motor_Control.ino
//
// Uses the TMC5160's built-in hardware ramp controller (velocity mode).
// No step pulses are generated by the MCU — the chip handles all timing.
// STEP_PIN and DIR_PIN wires can stay connected; they are simply unused.
//
// Serial protocol (115200 baud):
//   Receive:  RPM:xxx.x\n   — ramp to target RPM
//             STOP\n        — decelerate to halt, disable driver
//   Send:     RPM_READY\n               — on boot
//             RPM_ACTUAL:xxx.x\n        — actual RPM every 200 ms (from VACTUAL)
//             STOPPED\n                 — once deceleration finishes
//
// Tuning notes:
//   AMAX 500  ≈ gentle ramp (~2-3 seconds to reach moderate speeds). Increase
//             to ramp faster; decrease for a longer, smoother climb.
//   VSTART/VSTOP must be > 0; they set the minimum step frequency so the
//             driver never requests a zero-frequency step (avoids stall on start).

#include <TMCStepper.h>
#include <SPI.h>

// ── Pin assignments ───────────────────────────────────────────────────────────
#define EN_PIN    4
#define CS_PIN    10
// MOSI=D11, MISO=D12, SCK=D13 used automatically by SPI.begin()
// DIR_PIN / STEP_PIN intentionally NOT defined — unused in velocity mode

// ── Driver config ─────────────────────────────────────────────────────────────
#define R_SENSE        0.022f
#define MOTOR_CURRENT  1500       // mA RMS

// ── Motion config ─────────────────────────────────────────────────────────────
#define STEPS_PER_REV  200
#define MICROSTEPS     32
#define F_CLK          12000000UL // TMC5160 internal clock (Hz)

// ── Ramp config ───────────────────────────────────────────────────────────────
#define AMAX_VAL   500   // acceleration magnitude — tune here
#define DMAX_VAL   500   // deceleration magnitude (matched)
#define VSTART_VAL  10   // minimum start velocity (avoid zero-freq step)
#define VSTOP_VAL   10   // minimum stop velocity

// ── VACTUAL reporting ─────────────────────────────────────────────────────────
#define ACTUAL_REPORT_MS  200     // send RPM_ACTUAL every 200 ms

// ─────────────────────────────────────────────────────────────────────────────
TMC5160Stepper driver(CS_PIN, R_SENSE);

bool    motorEnabled  = false;
bool    stopping      = false;
float   targetRPM     = 0.0f;
String  inputBuffer   = "";

unsigned long lastReportMs = 0;


// Convert RPM to TMC5160 VMAX register value
uint32_t rpmToVmax(float rpm) {
  if (rpm <= 0.0f) return 0;
  float stepsPerSec = (rpm * (float)STEPS_PER_REV * (float)MICROSTEPS) / 60.0f;
  // VMAX unit: microsteps per (2^24 / fCLK) seconds
  return (uint32_t)(stepsPerSec * (float)(1UL << 24) / (float)F_CLK);
}

// Convert VACTUAL register value to RPM
float vactualToRpm(int32_t vactual) {
  if (vactual == 0) return 0.0f;
  float stepsPerSec = (float)vactual * (float)F_CLK / (float)(1UL << 24);
  return (stepsPerSec * 60.0f) / ((float)STEPS_PER_REV * (float)MICROSTEPS);
}

void enableDriver() {
  digitalWrite(EN_PIN, LOW);
  motorEnabled = true;
}

void disableDriver() {
  digitalWrite(EN_PIN, HIGH);
  motorEnabled = false;
}

void setup() {
  Serial.begin(115200);

  pinMode(EN_PIN, OUTPUT);
  disableDriver();

  SPI.begin();
  driver.begin();

  driver.toff(5);
  driver.blank_time(24);
  driver.rms_current(MOTOR_CURRENT);
  driver.microsteps(MICROSTEPS);
  driver.en_pwm_mode(false);
  driver.pwm_autoscale(true);

  // Velocity-mode ramp registers
  driver.VSTART(VSTART_VAL);
  driver.VSTOP(VSTOP_VAL);
  driver.AMAX(AMAX_VAL);
  driver.DMAX(DMAX_VAL);
  driver.VMAX(0);
  driver.RAMPMODE(1);   // 1 = velocity mode (positive direction)

  Serial.println("RPM_READY");
}

void loop() {
  // ── Serial command parsing ────────────────────────────────────────────────
  while (Serial.available()) {
    char c = Serial.read();
    if (c == '\n') {
      inputBuffer.trim();

      if (inputBuffer.startsWith("RPM:")) {
        float rpm = inputBuffer.substring(4).toFloat();
        if (rpm > 0.0f) {
          targetRPM = rpm;
          stopping  = false;
          if (!motorEnabled) enableDriver();
          driver.RAMPMODE(1);
          driver.VMAX(rpmToVmax(rpm));
        }

      } else if (inputBuffer == "STOP") {
        stopping  = true;
        targetRPM = 0.0f;
        driver.VMAX(0);   // chip decelerates via DMAX then holds at 0
      }

      inputBuffer = "";
    } else {
      inputBuffer += c;
    }
  }

  // ── VACTUAL reporting ─────────────────────────────────────────────────────
  unsigned long now = millis();
  if (now - lastReportMs >= ACTUAL_REPORT_MS) {
    lastReportMs = now;

    int32_t vact = (int32_t)driver.VACTUAL();
    float   rpm  = vactualToRpm(vact);

    Serial.print("RPM_ACTUAL:");
    Serial.println(rpm, 1);

    // Detect deceleration complete after STOP command
    if (stopping && vact == 0) {
      stopping = false;
      disableDriver();
      Serial.println("STOPPED");
    }
  }
}
